default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost  
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: projectapi
  attachments:
    <<: *default
    database: projectapi

production:
  # <<: *default
  primary:
    <<: *default
    database: projectapi
  attachments:
    <<: *default
    database: projectapi